version: "3.7"
services:

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/:/etc/prometheus/
    restart: always
    networks:
      testing_net:
        ipv4_address: 172.28.1.4
    
  alertmanager:
    image: prom/alertmanager
    volumes:
      - ./alertmanager/:/etc/alertmanager
    command:
      - '--config.file=/etc//alertmanager/alertmanager.yml'
    ports:
      - 9093:9093
    networks:
      testing_net:
        ipv4_address: 172.28.1.5

  grafana:
    image: grafana/grafana
    user: "104"
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning
    restart: always
    networks:
      testing_net:
        ipv4_address: 172.28.1.6


  node_alice:
    image: wpank/polkadot-super-fast:latest
    ports:
      - 30335:30335
      - 9946:9946
      - 9935:9935
    volumes:
      - "polkadot-data-alice:/alice"
    command:
      polkadot --chain=polkadot-local --validator --unsafe-ws-external --rpc-methods=Unsafe --rpc-external=True --ws-port 9946 --rpc-port 9935 --rpc-cors all --pruning archive --alice --node-key aa788920201122290fc7d3faf00698d9a8e061d7173424da2a31a8130a882a5f
    networks:
      testing_net:
        ipv4_address: 172.28.1.1


  node_bob:
    image: wpank/polkadot-super-fast:latest
    ports:
      - 30334:30334
      - 9945:9945
      - 9934:9934
    volumes:
      - "polkadot-data-bob:/bob"
    command:
      polkadot --chain=polkadot-local --validator --pruning archive --bob --bootnodes /ip4/172.28.1.1/tcp/30335/p2p/12D3KooWCJC43YRmb5WJcJmskPSxbkWY4Vp6jPKdFeggnXPxgBCw --port 30334 --ws-port 9945 --rpc-port 9934 --unsafe-ws-external --rpc-methods=Unsafe --rpc-external=True --rpc-cors all
    networks:
      testing_net:
        ipv4_address: 172.28.1.2


  node_charlie:
    image: wpank/polkadot-super-fast:latest
    ports:
      - 30336:30336
      - 9944:9944
      - 9933:9933
    volumes:
      - "polkadot-data-charlie:/charlie"
    command:
      polkadot --chain=polkadot-local --validator --pruning archive --charlie --bootnodes /ip4/172.28.1.1/tcp/30335/p2p/12D3KooWCJC43YRmb5WJcJmskPSxbkWY4Vp6jPKdFeggnXPxgBCw --port 30334 --ws-port 9944 --rpc-port 9933 --unsafe-ws-external --rpc-methods=Unsafe --rpc-external=True --rpc-cors all
    networks:
      testing_net:
        ipv4_address: 172.28.1.3




volumes:
  polkadot-data-alice:
  polkadot-data-bob:
  polkadot-data-charlie:

networks:
  testing_net:
      ipam:
          driver: default
          config:
              - subnet: 172.28.0.0/16
